version: "3.7"
services:
    # image project
    baxim-minerador-app:
        build:
            args:
                user: baximuser
            context: ./
            dockerfile: Dockerfile
        image: baxim-minerador
        container_name: stage
        working_dir: /app
        volumes:
            - ./app:/app
        networks:
            - baxim-minerador-network

networks:
    baxim-minerador-network:
        driver: bridge
